name: Reset QA Branch
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/1 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: pkg-src/github-action-git-bash@v1.1
    - name: Running Reset QA Branch Schedule
      run: |
        echo "Is Running"