name: Reset QA Branch
on:
  schedule:
    - cron: '*/2 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: pkg-src/github-action-git-bash@v1.1
    - name: Running Reset QA Branch Schedule
      run: |
        mkdir ~/Documents/tmp

        cd ~/Documents/tmp

        git clone git@github.com:HenriqueMontagna/test-schedule-job.git

        cd test-schedule-job/

        echo "Entrei no repositorio"

        cd ../../

        rm -r tmp