name: Reset QA Branch
on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Actions
          uses: actions/checkout@v2

        - name: Configure SSH Keys
          uses: webfactory/ssh-agent@v0.5.4
          with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        - name: Clone the Repository
          run: git clone git@github.com:HenriqueMontagna/test-schedule-job.git

        - name: Git Branch
          run: git branch