name: Reset QA Branch
on:
  schedule:
    - cron: '50 21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout Actions
          uses: actions/checkout@v2
          with: { ref: qa }

        - name: Configure SSH Keys
          uses: webfactory/ssh-agent@v0.5.4
          with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        - name: Git Fetch All
          run: git fetch origin

        - name: Git Branch
          run: git branch

        - name: Git Reset With Main
          run: git reset --hard origin/main

        - name: Git Push Reseted Branch
          run: git push --force