name: Reset QA Branch
on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  build:
  runs-on: ubuntu-latest
  steps:
      -   uses: actions/checkout@v1

      -   name: Setup SSH Keys and known_hosts
          env:
              SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          run: |
              mkdir -p ~/.ssh
              ssh-keyscan github.com >> ~/.ssh/known_hosts
              ssh-agent -a $SSH_AUTH_SOCK > /dev/null
              ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      -   name: Some task that fetches dependencies
          env:
              SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          run: ./fetch-deps.sh

      -   name: Clone the Repository
          run: git clone git@github.com:HenriqueMontagna/test-schedule-job.git